## These functions create a vector containing a matrix, its helper functions, and 
## functions to create, cache, and access the inverse of a matrix

## makeCacheMatrix - create a vector containing a matrix and helper functions to 
## get and set its internal data.

makeCacheMatrix <- function(x = matrix()) {
  ## Create cache variables
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  ## Helper functions to get / set cache data
  get <- function() x
  setinv <- function(inv) m <<- inv
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## cacheSolve - access a cached matrix inverse if it exists. If it does not
## perform the solve function and cache it within the vector generated by
## makeCacheMatrix

cacheSolve <- function(x, ...) {
  ## Check for existence cached data
  m <- x$getinv()
  if(!is.null(m)) {
    ## Cached data found, return it
    message("getting cached data")
    return(m)
  }
  ## Cached data not found. Solve the matrix and cache it for later
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
